### ISSUE TITLE
ImportError: No module named collectd

### ISSUE THREAD

**Issue by arunraman** [signalfx/collectd-openstack#3]
I am trying to run the test_openstack.py and I get this error. 

Traceback (most recent call last):
  File "test_openstack.py", line 7, in <module>
    import openstack_metrics
  File "/usr/lib/collectd/collectd-openstack/openstack_metrics.py", line 1, in <module>
    import collectd
ImportError: No module named collectd

So i tried to pip install collectd and i am not sure if thats the collectd package that it exepts, because it errors out on 

Traceback (most recent call last):
  File "test_openstack.py", line 7, in <module>
    import openstack_metrics
  File "/usr/lib/collectd/collectd-openstack/openstack_metrics.py", line 166, in <module>
    collectd.register_config(config_callback)
AttributeError: 'module' object has no attribute 'register_config'

I tried to search for collectd-python, but i can't find any. Which collectd should i install for this to work ?

**Comment by rmfitzpatrick** [comment]
The collectd module is made available while running in the [Python plugin context](https://collectd.org/documentation/manpages/collectd-python.5.shtml).  Looks like the intention of the test is to mock it in sys.modules but this should happen before importing `openstack_metrics`.  Not being too familiar with this test setup, it also looks like the testing flag isn't sourced in the mocked config either.

@prasadadireddi, are you able to speak to the readiness of this suite and any known configuration requirements?

**Comment by arunraman** [comment]
I got this work, the issue is the plugin is referring to some other register_config. The trick is to move the plugin to some other folder from /usr/lib/collectd and refer that path in the module like this

<Plugin python>
  ModulePath "/usr/share/collectd/openstack-collectd"
